/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


var TakikomiGohan={
    "imagen":"Takikomi gohan3.jpg",
    "titulo":"Takikomi gohan",
    "subtitulo":"Arroz con verduras y pollo",
    "bajada":"El takikomi gohanes otro plato bastante popular en todo Japón y es ideal para que lo hagas en casa y sorprender a todos con una auténtica receta japonesa. Se trata de un plato que tiene como ingrediente principal al arroz y está hecho con diversos tipos de verduras de temporada.",
    "pais":"Japón",
    "dificultad":"media",
    "momentoDia":"almuerzo",
    "tiempo":10,
    "ingredientes":["2 tazas y cuarto de arroz de grano redondo (tipo paella)",
    "4 setas shiitake",
    "1/4 gobo (raíz de bardana)",
    "1/4 konnyaku (gelatina japonesa)",
    "1 zanahoria de 7 centímetros",
    "120g de muslo de pollo sin hueso",
    "1 cucharada de sake",
    "2 cucharadas de salsa de soja",
    "1 cucharadita de salsa de soja",
    "1 cucharada de mirin","1/2 cucharadita de sal"],
    "preparacion":["Lava al arroz en un colador. Dejalo de lado.",
    "Corta el pollo en pequeños trozos. Condimenta el pollo con una cucharadita de salsa de soja.",
    "Filetea el gobo en rebanadas finas y mételo en agua durante unos minutos. Escurre el gobo.",
    "Hierve el konnyaku y córtalo en pequeños rectángulos.",
    "Pela la zanahoria y córtala en pequeños rectángulos.",
    "Quitale tallos a las setas shiitake y córtalas también en rebanadas finas.",
    "Pon 2 taza y media de agua en una cazuela. Añada el sake, el mirin, las 2 cucharadas de salsa de soja, y la sal.",
    "Calienta la sopa. Añade el pollo, la zanahoria, el gobo, las setas shiitake y el konnyaku en la sopa. Cuécelo todo a fuego lento durante aproximadamente cinco minutos. Retira cualquier espuma o impurezas que se eleve a la superficie. Apaga el fuego y deja enfriar.",
    "Separa los ingredientes cocidos de la sopa usando un colador. Añade un poco de agua en la sopa para hacer 2 taza y 1/2 de líquido. Vierte el líquido sobre el arroz. Cuece a fuego lento con los ingredientes sobre el arroz, hasta que esté cocinado."
]
};

var ButaNoShogayaki={
    "imagen":"Buta no Shogayaki4.jpg",
    "titulo":"Buta no Shogayaki",
    "subtitulo":"Cerdo al jengibre",
    "bajada":"La carne de cerdo y el jengibre son dos ingredientes que, a priori, puede que no creas que encajan bien juntos. Sin embargo existe un plato japonés muy sencillo de preparar en casa y muy sabroso con estos dos ingredientes como base. ",
    "pais":"Japón",
    "dificultad":"facil",
    "momentoDia":"almuerzo",
    "tiempo":15,
    "ingredientes":["450g en lonchas finas de carne de cerdo",
    "2 cucharadas de jengibre fresco rallado",
    "3 cucharadas de salsa de soja",
    "2 cucharadas de mirin",
    "1 cucharada de sake"],
    "preparacion":["Mezclar la salsa de soja, el mirin, el sake y jengibre rallado en un tazón.",
    "Marina la carne de cerdo durante un mínimo de 15 minutos en la mezcla.",
    "Caliente un poco de aceite en una sartén. Fríe la carne de cerdo a fuego medio removiendo contínuamente, retira el cerdo de la sartén.",
    "Ahora añade la salsa restante de la mezcla anterior y llévala a ebullición un rato, añade la carne de cerdo y déjalo que cueza todo junto un rato.",
    "Sirve la carne de cerdo acompañada de arroz o con col finamente cortada."]
};

var KatSukare={
    "imagen":"Katsu kare2.jpg",
    "titulo":"Katsu kare",
    "subtitulo":"Cerdo con arroz y curry",
    "bajada":"Hoy preparamos una deliciosa receta de curry japonés o katsu-kare. Una receta sabrosa y reconfortante que me encanta preparar en casa.  Cuando estuve en Japón comimos curry al estilo japonés en varios sitios y fue de nuestros platos favoritos durante nuestro viaje.",
    "pais":"Japón",
    "dificultad":"media",
    "momentoDia":"almuerzo",
    "tiempo":10,
    "ingredientes":["4 trozos de tonkatsu *ver receta más abajo",
    "3 tazas de arroz hervido o al vapor",
    "650ml de agua",
    "100g de curry japonés"],
    "preparacion":["Cocina los tonkatsu y resérvalos.",
    "Calienta en un cazo o sartén el agua y diluye el curry japonés hasta que no queden grumos. Añade más agua si te gusta menos espeso. Resérvalo.",
    "Corta los tonkatsu a lo ancho en aproximadamente 2 cm de largo.",
    "Coloca un poco del arroz en uno los extremos de cada plato.",
    "Coloca una chuleta de tonkatsu cortado en el centro de cada plato.",
    "En el otro extremo vierte el curry, hasta casi la mitad del plato empapando medio tonkatsu. Servir.",
]
};
var InariSushi={
    "imagen":"Inari sushi.jpg",
    "titulo":"Inari sushi",
    "subtitulo":"Bolsitas de tofu frito",
    "bajada":"El inarizushi o sushi inari es una variedad de sushi relleno. No es muy conocido y rara vez podremos encontrarlos en restaurantes de sushi debido a que es un plato más propio del hogar.Suele ser el plato infaltable en cualquier picnic de fin de semana gracias a su agradable sabor y a su reducido tamaño.",
    "pais":"Japón",
    "dificultad":"dificil",
    "momentoDia":"cena",
    "tiempo":20,
    "ingredientes":["1 taza y media de arroz de grano redondo (tipo paella)",
    "1 taza y 2/3 de agua",
    "3 cucharadas de vinagre",
    "1 cucharada y media de azúcar",
    "Media cucharadita de sal",
    "2 cucharadas de semillas de sésamo",
    "6 aburaage (bolsitas de tofu frito)",
    "1 taza de caldo dashi o shojin dashi",
    "2 cucharadas y media de azúcar",
    "2 cucharadas de mirin",
    "2 cucharadas de salsa de soja"],
    "preparacion":["Lava el arroz con agua en un colador hasta que ésta salga clara.",
    "Pon el agua y el arroz en un cazo. A continuación, poner a hervir al máximo hasta que el agua hirviendo esté a punto de salirse.",
    "Una vez llegados a este punto, pon el fuego al mínimo 10 minutos más.",
    "Durante todo el proceso de cocción y reposo del arroz, preferiblemente la tapa no deberá ser retirada.",
    "Una vez pasados los 10 minutos, retira la tapa y dejalo reposar de 5 a 10 minutos más.",
    "Mientras tanto, poner a calentar (hasta disolverse) la sal, el azúcar y el vinagre de arroz.",
    "Una vez cocido el arroz, colocalo en un cuenco. Acto seguido rociálo con el sirope recién preparado. Mezclar poco a poco hasta que el arroz quede bien empapado de él.",
    "Una vez acabada la preparación del arroz, se deja tapado con un trapo húmedo para que no se reseque hasta que se enfríe.",
    "Mezclar el sésamo en el arroz de sushi.",
    "Poner el aburaage en agua hirviendo durante un momento para quitar el exceso de aceite. Escúrrelo y sécalo con papel.",
    "Corta el aburaage en mitades de modo que cada trozo tenga una obertura lateral.",
    "Pon en una cazuela el dashi, el azúcar, el mirin, y la salsa de soja y llévalo a ebullición. Añade el aburaage en la cazuela y ponlo a fuego lento. Tápalo y déjalo cocer hasta que el caldo casi se haya consumido. Para el fuego y déjalo enfriarse un ratito.",
    "Mójate las manos y haz pequeños montones de arroz de sushi.",
    "Coge un aburaage y presiónalo ligeramente para quitar el líquido en exceso. Abre la bolsita y llénala con un montón de arroz de sushi dentro. Pliega en el lado abierto para cerrar la bolsita.",
    "Repite la operación para el resto de aburaage."]
};
var FlautasConSalsaDePalta={
    "imagen":"Flautas con salsa de palta2.jpg",
    "titulo":"Flautas con salsa de palta",
    "subtitulo":"Flautas de pollo con una espectacular salsa de aguacate",
    "bajada":"LAS RECETAS DE POLLO MEXICANAS SE HICIERON PARA DISFRUTARLAS AL MÁXIMO, COMO ESTAS FLAUTAS DE POLLO CON SALSA DE AGUACATE. ¡TOMA NOTA!",
    "pais":"México",
    "dificultad":"media",
    "momentoDia":"almuerzo",
    "tiempo":20,
    "ingredientes":["1 pechuga de pollo rostizado, deshebrada",
    "12 tortillas de maíz",
    "4 cucharadas de queso fresco rallado",
    "2 tazas de lechuga picada, desinfectada",
    "Aceite vegetal",
    "1 aguacate pelado",
    "de taza de aceite de oliva",
    "2 tomates verdes",
    "1 cucharada de jugo de limón",
    "Sal y pimienta al gusto"],
    "preparacion":["Sofríe el pollo en una sartén con poca grasa, retíralo, distribúyelo entre las tortillas y enróllalas apretadamente para hacer las autas.",
    "Fríelas en aceite su ciente hasta que estén doradas y escurre el exceso de grasa.",
    "Para hacer la salsa: licua la pulpa de aguacate, los tomates, el jugo de limón y el aceite (si es necesario, añade un poco de agua), vacía a una salsera para que cada comensal se sirva.",
    "Acomoda las autas sobre una cama de lechuga, báñalas con la salsa y espolvorea el queso."]
};
var TacosDeSuadero={
    "imagen":"Tacos de suadero.jpg",
    "titulo":"Tacos de suadero",
    "subtitulo":"carne del pecho de la vaca, muslos con piel",
    "bajada":"De la variedad de tacos que encontrarás en la Ciudad de México, los tacos de Suadero deben ser una de las opciones más populares, junto con los tacos al Pastor; esta será una opción muy fácil de preparar para tu próxima noche de tacos. La carne es muy sabrosa, aunque se necesita un poco más de tiempo para cocinar, por lo general la puedes guisar con un poco de grasa hasta que esté tierna y  ligeramente frita en la grasa. ",
    "pais":"México",
    "dificultad":"media",
    "momentoDia":"almuerzo",
    "tiempo":30,
    "ingredientes":["18 tortillas de maíz",
    "2 kg de suadero lavado",
    "1 litro de leche",
    "2 hojas de laurel",
    "5 pimientas rojas",
    "Sal al gusto"],
    "preparacion":["En un recipiente mezcla la leche con 1 litro de agua y sal, incorpora el suadero y deja marinar durante 30 minutos, mínimo. ",
    "Escurre la carne y cocínala en agua suficiente con el laurel, las pimientas y 1 cucharada de sal hasta que esté suave; escúrrela y pícala.",
    "Fríe el suadero en aceite y cuando esté dorado, repártelo entre las tortillas y acompaña con cilantro, cebolla, limón y salsa de tu preferencia."]
};
var EnchiladasDeMoleConPollo={
    "imagen":"Enchiladas de mole con pollo3.jpg",
    "titulo":"Enchiladas de mole con pollo",
    "subtitulo":"vegetales con caldo de pollo",
    "bajada":"¿Quieres comer algo buenísimo? Estas enchiladas de mole con pollo harán que hasta repitas plato. Conoce qué es lo que necesitas para comenzar a prepararlas y disfruta de una gran comida.",
    "pais":"México",
    "dificultad":"facil",
    "momentoDia":"cena",
    "tiempo":25,
    "ingredientes":["4 1/2 tazas de caldo de pollo",
    "1 taza de aceite vegetal",
    "12 tortillas",
    "2 tazas de pollo cocido y deshebrado",
    "1 taza de crema",
    "1 taza de queso fresco desmoronado",
    "1/2 taza de cebolla en rebanadas",
    "1 vaso de mole rojo en pasta "],
    "preparacion":["En una olla, coloca el aceite y caliéntalo muy bien. Fríe las tortillas ligeramente; reserva en papel absorbente.",
    "Coloca el caldo de pollo en una olla, hiérvelo y agrega la pasta. Disuélvela hasta que el mole rojo esté líquido.",
    "Calienta el pollo en otra sartén.",
    "En el mole rojo caliente, sumerge cada una de las tortillas y pon un poco de pollo al centro de cada una.",
    "Te sugerimos servir tres enchiladas por porción.",
    "Decora con crema, queso y cebolla. Sirve inmediatamente."]
};
var TostadasDeTinga={
    "imagen":"Tostadas de tinga2.jpg",
    "titulo":"Tostadas de tinga",
    "subtitulo":"tostadas con pollo, frijoles, cebolla y queso",
    "bajada":"Las tostadas de tinga de pollo son una delicia muy mexicana. Puedes acompañarlas con frijoles, un poco de queso y una salsa verde muy picante. ¿No se te hizo agua la boca con sólo imaginarlas? Sigue nuestra receta y aprende a cocinarlas.",
    "pais":"México",
    "dificultad":"media",
    "momentoDia":"desayuno",
    "tiempo":20,
    "ingredientes":["1 pechuga de pollo",
    "1 cebolla cortada en tiras delgadas",
    "2 dientes de ajo picados",
    "3 chiles chipotles",
    "5 jitomates",
    "1 hoja de laurel",
    "8 tostadas",
    "1 taza de frijoles refritos",
    "Lechuga picada",
    "1/2 taza de crema",
    "1/4 de queso crema",
    "Rebanadas de aguacate",
    "Sal",
    "Aceite"],
    "preparacion":["En una olla pon a cocer la pechuga de pollo con un poco de sal. Posteriormente deshébrala y reserva.",
    "En una sartén con aceite sofríe el ajo y la cebolla. Mientras tanto licúa el jitomate, el chile chipotle y el caldo de pollo que sobró al hervir la pechuga.",
    "Una vez que tengas la mezcla añádela al sartén con las cebollas y el ajo. Agrega una hoja de laurel y la pechuga de pollo deshebrada. Déjalo cocer durante 20 minutos aproximadamente.",
    "Para servir coloca sobre las tostadas un poco de frijoles, agrega la tinga de pollo y decora con lechuga, crema, queso, aguacate y salsa de tu preferencia."]
};
var Miniquesadillas={
    "imagen":"Miniquesadillas.jpg",
    "titulo":"Miniquesadillas",
    "subtitulo":"miniquesadillas de chicharrón con frijolitos",
    "bajada":"Hazte una experto en preparar miniquesadillas de chicharrón con frijolitos y de vez en cuando date el permiso de comer un antojito mexicano o de explotar todas las recetas de comida mexicana que quieras.",
    "pais":"México",
    "dificultad":"facil",
    "momentoDia":"almuerzo",
    "tiempo":10,
    "ingredientes":["2 c de chicharrón prensado",
    "1 c de frijoles refritos",
    "kilo de masa de maíz",
    "Aceite para freír",
    "1 c de guacamole para servir"],
    "preparacion":["Mezcla el chicharrón prensado con los frijoles.",
    "Ayúdate de un tortillero para aplastar la masa y formar tortillas gruesas. Coloca al centro el relleno de chicharrón y ciérralas en la orilla para que puedas freírlas sin que se desborden.",
    "Con el aceite bien caliente, fríe las quesadillas hasta que doren. Reserva en papel absorbente.",
    "Acompaña con el guacamole."]
};
var EspaguetisEnSalsaPestoCasera={
    "imagen":"Espaguetis en salsa pesto casera.jpg",
    "titulo":"Espaguetis en salsa pesto casera",
    "subtitulo":"pasta preparada con salsa de color verde de albahaca",
    "bajada":"Los espaguetis al pesto, consisten en esta popular pasta, preparada con esta salsa de color verde. La albahaca, es el ingrediente que tornará a nuestros espaguetis de este susodicho color. El pesto es una salsa con mucha personalidad. Tanto por el color como por el sabor. El ajo y el queso le darán un toque potente mientras que la albahaca, le dará un toque anisado.",
    "pais":"Italia",
    "dificultad":"media",
    "momentoDia":"almuerzo",
    "tiempo":15,
    "ingredientes":["400g de espaguetis",
    "150g de hojas de albahaca. No incluyas el tallo, que amarga",
    "300g de queso parmesano",
    "2 dientes de ajo",
    "100g de piñones",
    "200ml de aceite de oliva",
    "Sal"],
    "preparacion":["Cocemos los espagueti. Añadimos un puñadito de sal en una cazuela con abundante agua hirviendo. Después añadimos los espagueti y los removemos con frecuencia, especialmente los primeros minutos de la cocción. Para que no se peguen al fondo",
    "Mientras se cuecen, preparamos la salsa pesto. En un vaso batidor ponemos la albahaca, el queso parmesano (u otro de tu gusto pero, mejor que sea curado. Con sabor), los dientes de ajo, los piñones, que puedes sustituirlos por nueces o almendras y el aceite de oliva. Lo batimos bien hasta que nos quede una salsa verde y bastante densa",
    "Ponemos la salsa en un bol grande. Y cuando los espaguetis estén al dente (tardarán unos 10 minutos de cocción), reservamos dos cucharones del caldo de la cocción. Unos 100ml. Y escurrimos los espaguetis del resto del agua",
    "Acto seguido, ponemos los espagueti en el bol donde habíamos puesto el pesto. Añadimos el caldo de la cocción, que darán a la salsa un toque más cremoso y sobre todo añadirá mucho sabor y con un tenedor mezclamos durante un par de minutos. Para que los espaguetis absorban bien toda la salsa."]
};
var PizzaCarboneraCasera={
    "imagen":"Pizza carbonera casera.jpg",
    "titulo":"Pizza carbonera casera",
    "subtitulo":"combinación de pizza y salsa carbonara",
    "bajada":"Realmente la llamamos carbonara porque es una creación comercial, pero en Italia este tipo de pizzas que no llevan tomate en su base se llaman “Pizza bianca”. Además hemos incorporado el nombre de carbonara gracias a nuestro grandioso error conocido (muy criticado por los italianos y con razón) de hacer la salsa carbonara con nata.",
    "pais":"Italia",
    "dificultad":"dificil",
    "momentoDia":"cena",
    "tiempo":30,
    "ingredientes":["250g de harina de trigo convencional",
    "125-140ml de agua",
    "10g de levadura de panadero fresca, o 4g de la seca",
    "una pizca de sal",
    "200ml de nata para cocinar",
    "1/2 cebolla",
    "150g de setas",
    "50g de panceta",
    "50g de queso parmesano rallado",
    "sal y pimienta negra recién molida"],
    "preparacion":["Preparamos la masa de la pizza. En un bol, ponemos la harina, la sal, la levadura y el agua. El agua es mejor añadírsela poco a poco. Lo que queremos, es una masa que se pegue un poquito a las manos. Tampoco demasiado pero sí algo. Si está muy seca, quedará una pizza muy dura después",
    "Mezclamos todos los ingredientes con una cuchara y sacamos la masa del bol. Ya sabes, que se pegue un poco a las manos. Amasamos durante alrededor de 10 minutos, hasta que quede una bola fina y suave.",
    "Devolvemos la masa al bol, tapamos y dejamos que fermente en algún lugar templado de la casa. Alrededor de 2 horas. Puedes acelerar este tiempo de fermentación añadiendo más levadura a la masa pero, si fermenta demasiado rápida, la pizza no obtendrá mucho aroma de la fermentación. Por eso es mi recomendación hacer una fermentación lenta",
    "Mientras fermenta podemos preparar la salsa carbonara. Para ello, en una sartén, ponemos la panceta cortada en cubos y sin nada de aceite. Calentamos y dejamos que se cocine a fuego fuerte durante un par de minutos. Pasado este tiempo, retiramos la panceta y reservamos, dejando la grasa que haya soltado",
    "Bajamos el fuego y en esta grasa, añadimos la cebolla bien picadita. Salpimentamos y cocinamos 5 minutos, removiendo con frecuencia y entonces añadimos las setas en trozos más bien grandes. Éstas tienden a encoger bastante una vez cocinadas. Cocinamos 5 minutos más.",
    "En este momento, añadimos la nata para cocinar. Rectificamos de sal y dejamos reducir alrededor de 10 minutos, a fuego suave, que la nata se quema con mucha facilidad.",
    " Pasado el tiempo, volvemos a meter la panceta, añadimos queso rallado y apagamos el fuego. Dejamos que se enfríe por completo",
    "Cuando la masa haya doblado de tamaño – dos horas después del inicio de la fermentación – la retiramos del bol y la colocamos en una encimera con un poco de harina. Le damos la forma deseada (aconsejo hacerlo con las manos, ya que con el rodillo las burbujas de la fermentación tienden a desaparecer. Pero hazlo como mejor te apañes) y encima colocamos nuestra salsa carbonara",
    "Mentemos la pizza en el horno previamente calentado a 200ºC. Dejamos que se cocine alrededor de 15 o 20 minutos. Hasta que la masa esté bien dorada y crujiente",
    "Retiramos la pizza carbonara casera del horno. Encima espolvoreamos con pimienta negra recién molida y con unos trocidos de queso parmesano ¡delicioso!"]
};
var TiramisuConHuevoCasero={
    "imagen":"Tiramisu.jpg",
    "titulo":"Tiramisú sin huevo casero",
    "subtitulo":"tiramisú muy parecido al original, e igual de rico",
    "bajada":"Pocos postres italianos hay tan internacionales y populares como el tiramisú y no es de extrañas pues es un dulce fácil, sencillo y tremendamente delicioso. Se puede tunear de muchas maneras y adaptarla a los gustos o necesidades de los comensales. De ahí viene nuestra receta de tiramisú sin huevo, dedicado a los alérgicos e intolerantes al mismo.",
    "pais":"Italia",
    "dificultad":"dificil",
    "momentoDia":"postre",
    "tiempo":30,
    "ingredientes":["1 paquete de bizcochos",
    "200ml de café express",
    "2 cucharadas de cacao en polvo",
    "200g de azúcar",
    "200ml de nata para montar",
    "500g de queso mascarpone",
    "1 cucharada de esencia de vainilla",
    "1 tableta de chocolate"],
    "preparacion":["Primero montamos la nata, bien fría, con unas varillas.",
    "En un recipiente, ponemos la nata para montar, bien fría. La puedes meter 10-15 minutos en el congelador para que se monte bien y rápido. Añadimos 150g del azúcar, y lo batimos todo con unas varillas, mejor si son eléctricas. Cuando la nata esté montada, dejamos de batir y la reservamos para el siguiente paso.",
    "Después mezclamos esta nata, con el queso mascarpone y la esencia de vainilla.",
    "Seguimos con el tiramisu sin huevo. En otro recipiente, ponemos el queso mascarpone. Sobre él, añadimos la esencia de vainilla y la nata ya montada. Lo mezclamos todo con una espátula, haciendo movimientos envolventes para evitar que la nata se desmonte. Cuando esté todo bien integrado, lo reservamos.",
    "Después, preparamos el líquido con el que mojaremos los bizcochos, la base de nuestro tiramisú.",
    "Sobre un plato, ponemos los 200ml de café exprés. Añadimos el cacao en polvo, el azúcar restante, y lo mezclamos hasta que todo se disuelva. Hecho esto, mojamos los bizcochos en el café. Cuando se hayan empapado, los colocamos sobre la fuente o el molde donde vamos a preparar nuestro tiramisú casero sin huevo.",
    "Ahora, hacemos las capas del tiramisú sin huevo, con la mezcla de nata y mascarpone y con más bizcochos bañados en café.",
    "Sobre estos bizcochos ponemos, a cucharadas, la mitad de la mezcla de nata y mascarpone que teníamos reservada. Sobre esta, ponemos otra capa de bizcochos bañados en café. Finalmente, añadimos una segunda capa de nata y mascarpone, hasta agotarla. Aunque si lo deseas, puedes ponerle más pisos al tiramisú casero sin huevo.",
    "Finalmente, espolvoreamos por encima el chocolate con leche y lo refrigeramos durante al menos 4 horas.",
    "Hecho esto, rallamos la tableta de chocolate y lo espolvoreamos por encima del tiramisú. Esto le dará un buen toque de sabor. Cuando hayamos terminado, introducimos el tiramisú a la nevera. Y lo dejamos enfriar durante un mínimo de 4 horas. Pasado este tiempo, estará listo para servir."]
};
var EnsaladaCesar={
    "imagen":"Ensalada cesar2.jpg",
    "titulo":"Ensalada cesar",
    "subtitulo":"receta casera con pollo",
    "bajada":"La ensalada César, una ensalada que tiene nombre propio, conocida en todo el mundo y que os enseñamos a preparar paso a paso para que os animéis a hacerla en casa. Sin duda, en esta ensalada lo más importante es la deliciosa salsa César, incluso la encontramos en la mayoría de los supermercados. Pero veréis que con nuestra receta de salsa César casera hacerla vosotros mismos no tiene secretos. Sin duda una ensalada fresca y sabrosa perfecta para cualquier ocasión.",
    "pais":"Italia",
    "dificultad":"dificil",
    "momentoDia":"almuerzo",
    "tiempo":5,
    "ingredientes":["2 lechugas romanas",
    "150ml de aceite de oliva",
    "1 huevo",
    "200g de queso parmesano",
    "jugo de 1/2 limón",
    "40g de anchoas en conserva",
    "1 cucharadita de mostaza",
    "1 diente de ajo",
    "100g de picatostes (pan tostado cortado en cubos)",
    "1 cucharadita de salsa inglesa «worcester»",
    "2 pechugas de pollo",
    "tomates cherrys (opcional)",
    "rúcula (opcional)",
    "Sal y pimienta",
    "chorrito de aceite de oliva más, para cocinar las pechugas"],
    "preparacion":["Lo más importante de esta receta: La salsa césar. Para preparla, en un vaso batidor ponemos el huevo, los 200ml de aceite de oliva, y el jugo del limon. Ponemos una batidora manual o turmix en el fondo del mismo y le damos «caña». Pasados 10 segundos, levantamos un poquito la batidora, sin parar de batir. Dejamos 5 segundos más y ya podemos subir y bajar continuamente la batidora, siempre sin parar de batir. Ya tendremos nuestra mayonesa hecha, la base de la salsa césar. Ten en cuenta que debe quedar algo líquida, porque le vamos a añadir a continuación más ingredientes.",
    "Para preparar nuestra salsa césar, añadimos a la mayonesa un diente de ajo, el jugo del limón, las anchoas, escurridas de su aceite, la mostaza, la salsa worcester, y unos 50g del queso parmesano. Volvemos a batir. Con estos ingredientes tan sólidos, tendremos una salsa con más cuerpo. Si te queda muy densa, puedes añadir un pequeño chorrito de leche y remover, hasta que quede una salsa con cierto cuerpecito pero, tirando a líquida",
    "Salpimentamos y cortamos las pechugas de pollo en cubos de tamaño de bocado. Las ponemos en una sartén, con un chorrito de aceite y a fuego fuerte, y las cocinamos unos minutos. Que cojan color por fuera y se cocinen en su interior.",
    "Mientras se cocina el pollo, vamos montando nuestra ensalada. En el fondo de una ensaladera, ponemos un par de cucharadas de la salsa cesar. sobre ella, la lechuga cortada en trozos, los tomates cherrys y la rúcula (estos dos últimos ingredientes, no son típicos de la ensalada cesar. Pero a mí, me encantan) los picatostes, el resto del queso parmesano, cortado en lascas finas y finalmente, el pollo, cuando esté totalmente cocinado. Terminamos aderezando con más salsa césar. Servir inmediatamente, porque el calor del pollo, le va a dar un toque de ensalada templada muy interesante."]
};
var PannaCottaDeCafé={
    "imagen":"Panna cotta de café.jpg",
    "titulo":"Panna cotta de café",
    "subtitulo":"nata cocida, que no lleva huevo",
    "bajada":"La panna cotta es un postre italiano, de origen piamontés, muy fácil de hacer y muy delicioso. Hoy te voy a enseñar a hacerlo de café, para que puedas comerlo después de almorzar o cenar como si te tomaras una taza de café. Tú lo puedes hacer mucho más dulce incrementando la cantidad de azúcar o más cargado, aumentando la cantidad de café. También lo puedes hacer descafeinado parea que no tengas problemas a la hora de conciliar el sueño.",
    "pais":"Italia",
    "dificultad":"facil",
    "momentoDia":"postre",
    "tiempo":20,
    "ingredientes":["800ml de nata para cocinar",
    "200ml de café",
    "50g de azúcar",
    "1 sobre de polvos para flan"],
    "preparacion":["Mezclamos los polvos de flan y el café para que no queden grumos",
    "En un vaso, ponemos el café templado y el preparado para flan. Lo mezclamos bien con una cucharilla hasta que los polvos se hayan disuelto por completo.",
    "Calentamos todo a fuego suave ¡sin que llegue a hervir!",
    "Después, en una cazuela, ponemos la nata, el azúcar y la mezcla que acabamos de preparar. Mezclamos bien y lo calentamos a fuego suave durante 5 minutos, removiendo con frecuencia. Cuando esté cerca de hervir apagamos el fuego.",
    "Llenamos las flaneras con la panna cotta de café líquida",
    "A continuación, vertemos la mezcla en moldes para flan. Dejamos que allí se enfríen durante 15-20 minutos y luego, los introducimos en la nevera durante al menos 2 horas. Pasado ese tiempo estarán listos."]
};
var PolloALaNaranja={
    "imagen":"Pollo a la naranja2.jpg",
    "titulo":"Pollo a la naranja",
    "subtitulo":"pechugas de pollo cocinadas junto a una salsa hecha a base de zumo de naranja",
    "bajada":"El pollo a la naranja es una comida típica de Asia. No tiene nada que ver con el pato al horno a la naranja, plato típico francés. En este caso, se trata de unas pechugas de pollo cocinadas junto a una salsa hecha a base de zumo de naranja. Se puede acompañar de un arroz blanco, que le va a venir «al pelo» a este plato.",
    "pais":"China",
    "dificultad":"media",
    "momentoDia":"cena",
    "tiempo":25,
    "ingredientes":["4 pechugas de pollo",
    "2 cebollas",
    "4 naranjas",
    "2 cucharadas de salsa de soja",
    "2 dientes de ajo",
    "1 chorrito de vinagre",
    "1 cucharada de azúcar",
    "2 cucharadas de maizena",
    "sal y pimienta",
    "aceite de oliva"],
    "preparacion":["Preparamos la salsa. Para ello, exprimimos las naranjas en un bol. Añadimos la salsa de soja, los dientes de ajo picados, el chorrito de vinagre, el azúcar, la maizena, que espesará la salsa en la cocción y un poco de sal y de pimienta negra recién molida. Puedes añadir aquí el pollo y dejarlo macerar durante una hora o, puedes pasar directamente al siguiente paso",
    "En una sartén a fuego medio, añadimos un chorrito de aceite. Cuando esté caliente añadimos la cebolla picada muy finamente. Salpimentamos y dejamos cocinar 5 minutos, mientras removemos de vez en cuando con una cuchara de palo",
    "Pasado el tiempo, subimos la potencia del fuego y añadimos las pechugas de pollo, que ya están previamente cortadas en tamaño de bocado y salpimentadas. Mezclamos con la cebolla y sellamos los taquitos durante un par de minutos.",
    "Hecho esto, añadimos la salsa que habíamos preparado al principio. Bajamos la potencia del fuego y vamos cocinando a fuego suave, mientras mezclamos con la cuchara. La salsa irá reduciéndose un poco mientras también se va espesando por efecto de la maizena. Finalmente, puedes espolvorear con perejil fresco."]
};
var PolloAgridulce={
    "imagen":"PolloAgridulce2.jpg",
    "titulo":"Pollo agridulce",
    "subtitulo":"pollo en cubos con cebolla, pimientos y ajo",
    "bajada":"Vamos a preparar un pollo agridulce chino. Pero no uno cualquiera. La receta original. En realidad es muy facil de hacer. ¿Quién necesita ir a los restaurantes de comida china, pudiendo preparselo en casa? Y ya vamos por unos cuantos, tanto en esta página web como en el canal de Youtube. Al final de este artículo, encontrarás otras recetas chinas que hemos preparado ya aquí. Pero de momento, vamos a ver cómo hacer en casa este pollo agridulce chino",
    "pais":"China",
    "dificultad":"media",
    "momentoDia":"cena",
    "tiempo":20,
    "ingredientes":["300g de pechuga de pollo",
    "1 huevo",
    "1 cucharada de salsa de soja",
    "1 cucharada de vino chino (vale vino blanco)",
    "1 pimiento rojo",
    "1 pimiento verde",
    "1 diente de ajo",
    "1/2 cebolla",
    "Maizena",
    "sal",
    "Aceite",
    "150ml de agua",
    "30g de kétchup",
    "2 cucharadas de salsa de soja",
    "1 cucharada de vinagre de arroz (o de vino si no tienes)",
    "15g de azúcar moreno",],
    "preparacion":["Cortamos el pollo en cubos más o menos grandes. De un tamaño un pelín más pequeño de bocado. Hacemos lo mismo con la cebolla y los pimientos. El ajo, lo picamos muy fino",
    "En un bol ponemos el huevo y lo batimos. Añadimos el pollo troceado y le añadimos una pizca de sal. Después añadimos la cucharada de vino blanco y la de soja. Mezclamos bien",
    "A continuación puedes dejar marinar esto en la nevera de 4 horas a un día entero. Pero si no quieres, puedes proseguir con la receta sin esperar más. Añadimos y cubrimos todo esto con generosa cantidad de maizena y mezclamos bien. Puedes también pasar cada trozo de pollo por la maizena en un plato aparte pero, la maizena es harina de maíz muy fina, y es un poco engorroso para las manos hacerlo así. Por eso prefiero añadírsela directamente, aunque gastemos mucha más cantidad de maizena de que la otra forma. Es más práctico",
    "Metemos en el congelador para que la masa repose y mientras tanto, preparamos la salsa agridulce que acompañará al pollo. Para ello, ponemos todos los ingredientes de la salsa, salvo la maizena, en una sartén. Calentamos mientras removemos con frecuencia. Dejamos que espese unos 10 minutos y reservamos",
    "Ahora, podemos volver a sacar las pechugas de pollo del congelador. Les retiramos el exceso de maizena y freímos cada pieza en abundante aceite muy caliente. Cuando estén doradas, las retiramos y las colocamos sobre papel absorbente",
    "En un wok o en una sartén grande, añadimos un chorrito de aceite. Lo calentamos a fuego medio y añadimos el diente de ajo picado. Justo cuando comienza a coger color, añadimos los pimientos, la cebolla y una pequeña cantidad de sal. Mezclamos todo bien mientras dejamos cocinar 3 minutos más.",
    "Es el momento de añadir la salsa agridulce. Añadimos también una cucharadita de maizena, disuelta en 10ml de agua. Esto es para que espese la salsa. Mezclamos bien y dejamos cocinar un par de minutos más, sin dejar de remover",
    "Añadimos el pollo. Volvemos a mezclar todos los ingredientes y servimos inmediatamente ¡Esta comida no espera!"]
};
var Congee={
    "imagen":"Congee.jpg",
    "titulo":"Congee",
    "subtitulo":"sopa espesa que tiene el arroz como protagonista",
    "bajada":"El congee casero es un plato tradicional de la cocina China. Se considera una de las recetas más antiguas de la humanidad, encontramos registros de esta preparación desde hace 2000 años. Se trata de una sopa espesa que tiene el arroz como protagonista. El arroz blanco se convertirá en esta combinación de sabores en el encargado de darle cierta textura a este plato de cuchara que se come como desayuno o cena en gran parte de Asia.",
    "pais":"China",
    "dificultad":"media",
    "momentoDia":"desayuno",
    "tiempo":30,
    "ingredientes":["150 gr de arroz Thai",
    "2 zanahorias",
    "1 cebolleta",
    "2 pechugas de pollo",
    "900 ml de agua o de caldo de pollo",
    "30 ml de vino blanco",
    "1 cucharadita de pimienta",
    "1 cucharadita de sal",],
    "preparacion":["Vamos a empezar esta deliciosa sopa de arroz preparando las verduras. Pelaremos y cortaremos las zanahorias muy finitas y las reservaremos mientras seguimos con el resto de los ingredientes.",
    "Repetiremos la operación con la cebolleta, un ingrediente que le dará un punto extra de sabor dulce y ese toque crujiente.",
    "Nos ponemos manos a la obra con las pechugas de pollo, les quitaremos cualquier pielecilla que puedan tener y las lavaremos bajo un buen chorro de agua fría. Si son muy grandes, troceamos las pechugas para que se integren mejor en esta sopa.",
    "Preparamos la olla. Ponemos el caldo de pollo o agua, siempre tendrá más sabor con el caldo que le dará mayor intensidad. Añadimos las zanahorias, el pollo y un poco de vino. Dejamos que estos ingredientes se cocinen a fuego lento durante unos 25 minutos.",
    "Rectificaremos de sal y pimienta para que tengan el sabor adecuado. Cuando el pollo esté cocinado lo retiramos del caldo y los troceamos. Reservamos para la fase final de este plato.",
    "Ponemos el arroz y dejamos que se cocine durante unos 20 minutos. Pasado este tiempo volvemos a poner el pollo a la sopa. Tendremos una sopa de arroz con pollo repleta de sabor, pero nos faltará el toque oriental.",
    "Servimos un cuenco de esta deliciosa sopa por persona. Debe estar especialmente caliente para disfrutarla. Por encima la decoramos con la cebolleta troceada para darle ese toque crujiente que nos interesa. Podemos añadirle unas gotitas de salsa de soja, el resultado será espectacular.",]
};
var CongYouBing={
    "imagen":"CongYouBing.jpg",
    "titulo":"Cong you bing",
    "subtitulo":" tipo de pan sin levadura hecho con harina de trigo, tradicional de la cocina china.",
    "bajada":"El bing se puede freír en una sartén o se puede cocinar a la parrilla. También se puede cocer en el horno, aunque esta versión no es tan común. Se parece a los panqueques, o a cualquiera otra crepe que se cocine con una masa preparada con harina de trigo sin levadura, en las cocinas china y occidental. Es similar al roti indio, a la crepe francesa o a la tortilla mexicana.",
    "pais":"China",
    "dificultad":"media",
    "momentoDia":"desayuno",
    "tiempo":30,
    "ingredientes":["500 g de harina",
    "230 ml de agua hirviendo",
    "60 ml de agua fría",
    "1 cucharadita de sal",
    "250 g de cebolletas",
    "1 cucharada de aceite de sésamo",
    "Aceite vegetal"],
    "preparacion":["Corte las cebolletas finamente. Mézclelas con aceite de sésamo, ½ cucharadita de sal y refrigere.",
    "Mezcle la harina y ½ cucharadita de sal. Vierta el agua hirviendo toda a la vez y mezcle con fuerza.",
    "A continuación, agregue el agua fría gradualmente y amase hasta obtener una masa suave, fina y homogénea. Deje reposar durante 45 minutos.",
    "Divida la masa en 10 partes. Con un rodillo, extienda cada trozo de masa hasta que tenga un espesor de aproximadamente 1,5 mm.",
    "Cepille cada trozo de masa con aceite. Espolvoree generosamente con cebollas frescas.",
    "Forme un palo largo con cada trozo de masa y enrolle los palos para formar caracoles. Deje reposar durante 30 minutos.",
    "Con el rodillo, aplane cada uno de los caracoles para formar círculos de 5 mm de espesor.",
    "Coloque una sartén ligeramente engrasada a fuego medio y cocine cada crepe de 3 a 4 minutos por cada lado."]
};
var ArrozTresDelicias={
    "imagen":"ArrozTresDelicias2.jpg",
    "titulo":"Arroz tres delicias",
    "subtitulo":"arroz cocido, junto a unas verduras, carne y tortilla (tres delicias)",
    "bajada":"El arroz tres delicias chino es un plato muy común en los restaurantes de comida china en España. Consiste en un arroz cocido, junto a unas verduras, carne y tortilla (tres delicias) que finalmente se frie en aceite muy caliente. Adicionalmente y aunque, yo lo he visto poco en los susodichos restaurantes, se le puede añadir soja. Le da un toque más oriental y más rico. Una de las cosas buenas que tiene este plato es que es muy fácil de hacer. Y también muy barato. A continuación, cómo hacer un arroz tres delicias chino.",
    "pais":"China",
    "dificultad":"media",
    "momentoDia":"almuerzo",
    "tiempo":30,
    "ingredientes":["800g de arroz alargado",
    "4 huevos",
    "4 zanahorias",
    "150g de guisantes",
    "150g de jamón cocido cortado en tacos",
    "6 cucharadas de salsa de soja (opcional)",
    "Aceite",
    "sal",],
    "preparacion":["Ponemos a cocer el arroz. Mejor si es de grano alargado que el redondo. Ponemos el doble de agua que de arroz y cuando rompa a hervir, añadimos el cereal junto con una pizca de sal. Removemos un poco al principio para que no pegue al fondo y dejamos cocer a fuego suave durante unos 20 minutos",
    "En otra olla en abundante agua hirviendo, añadimos la zanahoria cortada en cubos y los guisantes. Si los guisantes son de lata no los añadas. Están cocidos ya. Añadimos una pizca de sal y dejamos cocer unos 10 minutos",
    "Mientras se cocinan estos ingredientes preparamos una tortilla francesa que va a acompañar a nuestro arroz tres delicias chino. La gracia de este plato está en que la tortilla quede muy fina. Ponemos unos huevos en un bol y les añadimos una pizca de sal. Después los batimos.",
    "Ponemos un chorrito de aceite en una sartén antiadherente ancha y dejamos que se caliente a fuego medio. Cuando esté caliente, añadimos el huevo batido y dejamos cocinar un par de minutos",
    "Pasado el tiempo le damos la vuelta a la tortilla con ayuda de un plato. Que se cocine por el otro lado. Y una vez esté bien cuajada por ambas caras, la sacamos con la ayuda de un plato y la reservamos.",
    "Cuando la zanahora y los guisantes (si no eran de lata) estén blandos, les escurrimos el agua. Hacemos lo mismo con el arroz",
    "Para finalizar, en un wok o en una sartén bien grande, ponemos un chorrito de aceite a calentar a fuego fuerte. Cuando humee un poco añadimos el arroz, los guisantes y la zanahoria. Añadimos también la tortilla cortada en cuadraditos. Añadimos unos tacos de jamón cocido y opcionalmente añadimos la salsa de soja. La salsa de soja añadirá mucho sabor, aparte de darle un toque más oscuro, como en la foto. Removemos todos los ingredientes constantemente mientras se cocinan a fuego fuerte durante un par de minutos."]
};
var TortaChajáClásica={
    "imagen":"chaja.jpg",
    "titulo":"Torta Chajá clásica",
    "subtitulo":"torta con base de crema chantilly, merengue, bizcochuelo, durazno y dulce de leche.",
    "bajada":"La torta chajá tiene sus orígenes entre los pueblos de Colón y Paysandú, separados por el río Uruguay. Su creación se le adjudica al propietario de una renombrada confitería uruguaya llamada “Las Familias”. Esta deliciosa receta de postre chajá debe su nombre al ave del mismo nombre, oriunda de América del Sur. Consiste en una base de crema chantilly, merengue, bizcochuelo, durazno y dulce de leche.",
    "pais":"Uruguay",
    "dificultad":"dificil",
    "momentoDia":"postre",
    "tiempo":40,
    "ingredientes":["6 huevos",
    "180 gramos de azúcar común",
    "180 gramos de harina",
    "1 lata de durazno en almíbar",
    " 500 gramos de dulce de leche repostero",
    "500 gramos de merengue",
    "500 centímetros cúbicos de crema de leche",
    "100 gramos de azúcar común",
    "Esencia de vainilla"],
    "preparacion":["Para preparar la torta chajá, deberás, en primer lugar, elaborar el bizcochuelo esponjoso. Reúne todos los ingredientes para ello.",
    "Bate los huevos junto con el azúcar hasta llegar a punto letra, es decir, hasta que, al levantar la espátula, puedas hacer una letra o una figura con el batido.",
    "Incorpora la harina con movimientos envolventes.",
    "En un molde enmantecado y enharinado, coloca la mezcla. Hemos utilizado uno de 24 cm de diámetro, pero si tienes un molde de 20 cm, también te servirá.",
    "Introduce el bizcochuelo de tu torta chajá en el horno, a 180 °C. Hornéalo por, aproximadamente, 30 o 40 minutos. Una vez frío, lo córtalo en 3 capas.",
    "Ahora, bate la crema, los 100 g de azúcar y la esencia de vainilla hasta que la crema quede montada.",
    "Es hora de rellenar el postre chajá! Cuela los duraznos y reserva el almíbar. Con el almíbar, moja la primera capa de la torta y, por encima, coloca el dulce de leche repostero.",
    "Rompe el merengue y colócalo sobre el dulce.",
    "Coloca, por encima, la segunda capa que cortaste del bizcochuelo y moja con el almíbar. Vuelca parte de la crema chantilly y reserva una parte para el forrado. Por encima de la crema, coloca los melocotones cortados en rodajas o en cubos.",
    "Pon una tercera y última capa de bizcochuelo sobre el postre. Nuevamente, repite el mismo procedimiento y coloca la crema restante, esparciéndola por todos los lados. Rompe más merengue y ve cubriendo la torta a lo largo de toda su superficie. Déjalo refrigerar por al menos 3 horas ¡y disfruta de esta deliciosa torta chajá!",
    ]
};
var bizcochuelo={
    "imagen":"bizcochuelo.jpg",
    "titulo":"Bizcochuelo",
    "subtitulo":"clásico bizcochuelo uruguayo en base de arina y huevos",
    "bajada":"El bizcochuelo no lleva ningún ingrediente graso y su preparación se hace en base a un intenso batido de huevos y azúcar. Se cocina preferentemente a fuego lento para evitar que se queme, se eleve más y su cocimiento se haga con mejores resultados.",
    "pais":"Uruguay",
    "dificultad":"facil",
    "momentoDia":"desayuno",
    "tiempo":35,
    "ingredientes":["6 huevos",
    "200 g azúcar",
    "200 g harina",
    "1 cdita. polvo de hornear",
    "Vainilla, c/n"],
    "preparacion":["Encienda el horno a temperatura media/baja, para precalentarlo. Enmantecar y enharinar el molde.",
    "Separar las claras de las yemas.",
    "Batir las yemas con el azúcar, a potencia máxima, hasta que la preparación haya duplicado su volumen, tenga color blanquecino y si se levanta un poco y se hace caer, forme una cinta espesa.",
    "Agregar la esencia de vainilla a gusto.",
    "Tamizar harina y el polvo para hornear sobre la preparación, incorporar con la espátula, mezclando con movimientos envolventes, de abajo hacia arriba, para que la preparación no se baje.",
    "Batir las claras a nieve e incorporar a la preparación con movimientos suaves y envolventes.",
    "Verter en el molde y hornear a temperatura moderada, unos 35 a 40 minutos.",
    "Importante: no abrir el horno hasta que hayan pasado 35 min. Para saber cuándo está cocido, los bordes se desprenden de las paredes del molde; además al introducir un palillo en la masa, salga limpio.",
    "Retirar del horno, dejar unos minutos para que baje la temperatura y desmoldar."]
};


var recetas=[TakikomiGohan, ButaNoShogayaki, KatSukare, InariSushi, FlautasConSalsaDePalta, TacosDeSuadero, EnchiladasDeMoleConPollo, TostadasDeTinga, Miniquesadillas, EspaguetisEnSalsaPestoCasera, PizzaCarboneraCasera, TiramisuConHuevoCasero, EnsaladaCesar, PannaCottaDeCafé, PolloALaNaranja, PolloAgridulce, Congee, CongYouBing, ArrozTresDelicias, TortaChajáClásica, bizcochuelo];

var uruguay={
    "pais":"Uruguay"
    
};
var china={
    "pais":"China"

};
var italia={
    "pais":"Italia"

};
var mexico={
    "pais":"México"
   
};
var japon={
    "pais":"Japón"
    
};

var paises=[uruguay, china, italia, mexico, japon];